# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
        args: ['--maxkb=2048']
-   repo: https://gitlab.com/pycqa/flake8
    rev: '5.0.4'  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
        args: ['--max-line-length=128', '--ignore=E127']
#-   repo: https://github.com/asottile/reorder_python_imports
#    rev: v2.6.0
#     hooks:
#     -   id: reorder-python-imports # remove before configured
