# Generated by Django 4.1.2 on 2022-11-01 11:02
from os import environ

from django.conf import settings
from django.db import migrations
from django.utils.crypto import get_random_string


def create_objects(apps, schema_editor):
    # Get models
    if settings.DEBUG:

        print("Creating demo profiles")
        CoreUser = apps.get_model(settings.AUTH_USER_MODEL)
        Profile = apps.get_model('core.Profile')
        SportClub = apps.get_model('core.SportClub')

        demo_pwd = environ.get(f"{settings.ENV_PREFIX}DEMO_PWD")
        if not demo_pwd:
            demo_pwd = get_random_string(length=10)
        print(f" demo password: {demo_pwd}")
        user = CoreUser.objects.create_superuser(email='spochan@example.com', username="Test Admin", password=demo_pwd)

        club_a = SportClub(name="Alpha", locality='St.Petersburg')
        club_b = SportClub(name="Beta", locality='Moscow')
        club_a.save()
        club_b.save()

        Profile.objects.create(owner=user, first_name='Vasiliy', last_name='Testov', club=club_a)
        Profile.objects.create(owner=None, first_name='Anna', last_name='Ivanova', club=club_b)
        Profile.objects.create(owner=None, first_name='Ivan', last_name='Petrov', middle_name='Ivanovich')

def clear_objects(apps, schema_editor):
    if settings.DEBUG:
        print("Clearing CoreUser and Profile models")
        CoreUser = apps.get_model(settings.AUTH_USER_MODEL)
        Profile = apps.get_model('core.Profile')
        SportClub = apps.get_model('core.SportClub')

        Profile.objects.all().delete()
        CoreUser.objects.all().delete()
        SportClub.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_objects, clear_objects),
    ]
