# Generated by Django 4.1.2 on 2022-11-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportDiscipline',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('is_certifiable', models.BooleanField(default=False)),
                ('priority', models.SmallIntegerField(default=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
