# Generated by Django 4.1.2 on 2023-01-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chanbara', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupType',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('is_primary', models.BooleanField(blank=True, default=False)),
                ('is_junior', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
