# Generated by Django 4.1.2 on 2022-11-01 13:11

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportCertificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('issued_date', models.DateField(default=datetime.date.today)),
                ('level', models.SmallIntegerField(choices=[(10, '10th kyu'), (20, '9th kyu'), (30, '8th kyu'), (40, '7th kyu'), (50, '6th kyu'), (60, '5th kyu'), (70, '4th kyu'), (80, '3rd kyu'), (90, '2nd kyu'), (100, '1st kyu'), (1100, '1st dan'), (1200, '2nd dan'), (1300, '3rd dan'), (1400, '4th dan'), (1500, '5th dan'), (1600, '6th dan'), (1700, '7th dan'), (1800, '8th dan'), (1900, '9th dan'), (2000, '10th dan')], db_index=True, default=10)),
            ],
            options={
                'verbose_name': 'sport certification record',
                'verbose_name_plural': 'sport certification records',
                'db_table': 'certification_sport_record',
            },
        ),
    ]
