# Generated by Django 4.2.5 on 2023-10-10 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('certification', '0001_initial'),
        ('chanbara', '0002_grouptype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sportcertificationrecord',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sportcertificationrecord',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certs', to='chanbara.sportdiscipline'),
        ),
        migrations.AddField(
            model_name='sportcertificationrecord',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.profile'),
        ),
    ]
