# Generated by Django 4.2.5 on 2024-03-19 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_chancode'),
        ('certification', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportcertificationrecord',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.profile'),
        ),
    ]
